services:
  - type: web
    name: cabinet_compta
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn cabinet_compta.wsgi:application --bind 0.0.0.0:$PORT
    rootDir: .