# Generated by Django 6.0.2 on 2026-09-30 09:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0025_urssafmensuelle_urssaftrimestrielle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestataireSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Prestataire social',
                'verbose_name_plural': 'Prestataires sociaux',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TypePrestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('tarif_client_standard', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tarif client standard')),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Type de prestation',
                'verbose_name_plural': 'Types de prestations',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PrestationSociale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveSmallIntegerField()),
                ('annee', models.PositiveSmallIntegerField()),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='Salarié / détail')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tarif_client_standard_snapshot', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tarif_client_applique', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tarif_personnalise', models.BooleanField(default=False)),
                ('motif_tarif_personnalise', models.CharField(blank=True, max_length=255)),
                ('cout_prestataire_unitaire_snapshot', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('montant_facture', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cout_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('marge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestations_sociales', to='dossiers.client')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestations_enregistrees', to='facturation_sociale.prestatairesocial')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestations_enregistrees', to='facturation_sociale.typeprestation')),
            ],
            options={
                'verbose_name': 'Prestation sociale',
                'verbose_name_plural': 'Prestations sociales',
                'ordering': ['-annee', '-mois', 'client__nom', 'prestation__nom'],
            },
        ),
        migrations.CreateModel(
            name='TarifPrestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Coût unitaire')),
                ('actif', models.BooleanField(default=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_prestations', to='facturation_sociale.prestatairesocial')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_prestataires', to='facturation_sociale.typeprestation')),
            ],
            options={
                'verbose_name': 'Tarif prestataire',
                'verbose_name_plural': 'Tarifs prestataires',
                'ordering': ['prestation__ordre', 'prestation__nom', 'prestataire__ordre'],
                'constraints': [models.UniqueConstraint(fields=('prestation', 'prestataire'), name='unique_tarif_prestataire_prestation')],
            },
        ),
    ]
