# Generated by Django 6.0.2 on 2026-09-30 13:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation_sociale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestationsociale',
            name='cout_prestataire_personnalise',
            field=models.BooleanField(default=False, verbose_name='Coût prestataire exceptionnel'),
        ),
        migrations.AddField(
            model_name='prestationsociale',
            name='cout_prestataire_standard_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Coût prestataire standard'),
        ),
        migrations.AddField(
            model_name='prestationsociale',
            name='motif_cout_prestataire_personnalise',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motif du coût prestataire exceptionnel'),
        ),
        migrations.AlterField(
            model_name='prestationsociale',
            name='cout_prestataire_unitaire_snapshot',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Coût prestataire appliqué'),
        ),
        migrations.AlterField(
            model_name='prestationsociale',
            name='detail',
            field=models.CharField(blank=True, max_length=255, verbose_name='SalariÃ© / dÃ©tail'),
        ),
        migrations.AlterField(
            model_name='tarifprestataire',
            name='cout_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='CoÃ»t unitaire'),
        ),
    ]
