# Generated by Django 6.0.2 on 2026-03-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0005_remove_notificationpaie_lu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClotureAnnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('clients', models.ManyToManyField(related_name='clotures', to='dossiers.client')),
            ],
        ),
    ]
