# Generated by Django 6.0.2 on 2026-03-13 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0001_initial'),
        ('dossiers', '0005_remove_notificationpaie_lu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_general', models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50)),
                ('termine', models.BooleanField(default=False)),
                ('pre_revision', models.TextField(blank=True, null=True)),
                ('statut_pre_revision', models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], max_length=50, null=True)),
                ('relance_pieces', models.TextField(blank=True, null=True)),
                ('statut_relance_pieces', models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], max_length=50, null=True)),
                ('releve_bancaire', models.TextField(blank=True, null=True)),
                ('statut_releve_bancaire', models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], max_length=50, null=True)),
                ('revision_ad', models.TextField(blank=True, null=True)),
                ('statut_revision_ad', models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.client')),
                ('cloture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloture.clotureannee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
