# Generated by Django 6.0.2 on 2026-03-14 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0007_modulemission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleplaquettesliasse',
            name='autres_documents',
        ),
        migrations.RemoveField(
            model_name='moduleplaquettesliasse',
            name='liasse_fiscale',
        ),
        migrations.RemoveField(
            model_name='moduleplaquettesliasse',
            name='plaquettes',
        ),
        migrations.RemoveField(
            model_name='moduleplaquettesliasse',
            name='statut_autres_documents',
        ),
        migrations.RemoveField(
            model_name='moduleplaquettesliasse',
            name='statut_liasse_fiscale',
        ),
        migrations.RemoveField(
            model_name='moduleplaquettesliasse',
            name='statut_plaquettes',
        ),
        migrations.RemoveField(
            model_name='moduleplaquettesliasse',
            name='termine',
        ),
        migrations.AddField(
            model_name='moduleplaquettesliasse',
            name='ca_152500',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moduleplaquettesliasse',
            name='liasse_envoi_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moduleplaquettesliasse',
            name='liasse_retour_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moduleplaquettesliasse',
            name='plaquette_envoi_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moduleplaquettesliasse',
            name='plaquette_retour_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moduleplaquettesliasse',
            name='statut_liasse_envoi_client',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50),
        ),
        migrations.AddField(
            model_name='moduleplaquettesliasse',
            name='statut_liasse_retour_client',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50),
        ),
        migrations.AddField(
            model_name='moduleplaquettesliasse',
            name='statut_plaquette_envoi_client',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50),
        ),
        migrations.AddField(
            model_name='moduleplaquettesliasse',
            name='statut_plaquette_retour_client',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='moduleplaquettesliasse',
            name='cloture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaquettes_liasse_modules', to='cloture.clotureannee'),
        ),
    ]
