# Generated by Django 6.0.2 on 2026-04-17 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0008_remove_moduleplaquettesliasse_autres_documents_and_more'),
        ('dossiers', '0005_remove_notificationpaie_lu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleJuridique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juridique_fait', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_juridique_fait', models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50)),
                ('juridique_envoi_client', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_juridique_envoi_client', models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50)),
                ('retour_client', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_retour_client', models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50)),
                ('envoi_greffe', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_envoi_greffe', models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50)),
                ('validation_greffe', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_validation_greffe', models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50)),
                ('statut_general', models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.client')),
                ('cloture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juridique_modules', to='cloture.clotureannee')),
            ],
        ),
    ]
