# Generated by Django 6.0.2 on 2026-06-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0010_modulerevision_liasse_envoi_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledeclarations',
            name='statut_cvae1329_envoi',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduledeclarations',
            name='statut_cvae1329_fait',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduledeclarations',
            name='statut_das2_fait',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduledeclarations',
            name='statut_decloyer_fait',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduledeclarations',
            name='statut_dri_envoi',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduledeclarations',
            name='statut_dri_fait',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduledeclarations',
            name='statut_general',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduledeclarations',
            name='statut_va1330_envoi',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduledeclarations',
            name='statut_va1330_fait',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier')], default='non_commence', max_length=50, null=True),
        ),
    ]
