# Generated by Django 6.0.2 on 2026-07-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0011_alter_moduledeclarations_statut_cvae1329_envoi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledeclarations',
            name='ca12_decl_cloture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moduledeclarations',
            name='is_decl_cloture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moduledeclarations',
            name='statut_ca12_decl_cloture',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='moduledeclarations',
            name='statut_is_decl_cloture',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduleca12',
            name='statut_ca12_envoyee',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='moduleca12',
            name='statut_ca12_faite',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='moduleca12',
            name='statut_general',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='moduledeclarations',
            name='statut_cvae1329_envoi',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduledeclarations',
            name='statut_cvae1329_fait',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduledeclarations',
            name='statut_das2_fait',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduledeclarations',
            name='statut_decloyer_fait',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduledeclarations',
            name='statut_dri_envoi',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduledeclarations',
            name='statut_dri_fait',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduledeclarations',
            name='statut_general',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduledeclarations',
            name='statut_va1330_envoi',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduledeclarations',
            name='statut_va1330_fait',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduleisci',
            name='statut_general',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='moduleisci',
            name='statut_is_envoi',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='moduleisci',
            name='statut_is_fait',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='modulejuridique',
            name='statut_envoi_greffe',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='modulejuridique',
            name='statut_general',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='modulejuridique',
            name='statut_juridique_envoi_client',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='modulejuridique',
            name='statut_juridique_fait',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='modulejuridique',
            name='statut_retour_client',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='modulejuridique',
            name='statut_validation_greffe',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='modulemission',
            name='statut_attestation',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='modulemission',
            name='statut_cr_mission',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='modulemission',
            name='statut_dossier_travail',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='modulemission',
            name='statut_general',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='modulemission',
            name='statut_lab_maintien',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='moduleplaquettesliasse',
            name='statut_general',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='moduleplaquettesliasse',
            name='statut_liasse_envoi_client',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='moduleplaquettesliasse',
            name='statut_liasse_retour_client',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='moduleplaquettesliasse',
            name='statut_plaquette_envoi_client',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='moduleplaquettesliasse',
            name='statut_plaquette_retour_client',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='modulerevision',
            name='statut_general',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], default='non_commence', max_length=50),
        ),
        migrations.AlterField(
            model_name='modulerevision',
            name='statut_liasse_envoi_client',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modulerevision',
            name='statut_plaquette_envoi_client',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modulerevision',
            name='statut_pre_revision',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modulerevision',
            name='statut_relance_pieces',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modulerevision',
            name='statut_releve_bancaire',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modulerevision',
            name='statut_revision_ad',
            field=models.CharField(blank=True, choices=[('non_commence', 'Non commencé'), ('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('a_envoyer_client', 'À envoyer au client'), ('en_attente_client', 'En attente du client'), ('a_envoyer_admin', "À envoyer à l'administration"), ('envoye', 'Envoyé / Transmis'), ('accepte', 'Accepté'), ('na', 'N/A'), ('ne_pas_modifier', 'Ne pas modifier'), ('termine', 'Terminé')], max_length=50, null=True),
        ),
    ]
