# Generated by Django 6.0.1 on 2026-01-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('forme_juridique', models.CharField(max_length=50)),
                ('regime_tva', models.CharField(max_length=50)),
                ('tva_applicable', models.BooleanField(default=True)),
                ('tvs_applicable', models.BooleanField(default=False)),
                ('cfe_applicable', models.BooleanField(default=True)),
            ],
        ),
    ]
