# Generated by Django 6.0.2 on 2026-03-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='regime_imposition',
            field=models.CharField(blank=True, choices=[('IS_RS', 'IS – Régime simplifié'), ('IS_RN', 'IS – Régime normal'), ('IR', 'IR'), ('MICRO', 'Micro'), ('IR_CRL', 'IR (CRL)')], max_length=20, null=True),
        ),
    ]
