# Generated by Django 6.0.1 on 2026-01-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='cfe_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='forme_juridique',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='regime_tva',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='tva_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
