# Generated by Django 6.0.2 on 2026-03-10 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.client')),
                ('paie_mois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paie.paiemois')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
