# Generated by Django 6.0.1 on 2026-01-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_client_archive_alter_client_cfe_applicable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cfe_applicable',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tva_applicable',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tvs_applicable',
        ),
        migrations.AddField(
            model_name='client',
            name='commentaires',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_cloture',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='periodicite',
            field=models.CharField(blank=True, choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel'), ('IRREGULIER', 'Irrégulier')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='regime_imposition',
            field=models.CharField(blank=True, choices=[('IS', 'IS'), ('IR', 'IR')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='forme_juridique',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='regime_tva',
            field=models.CharField(choices=[('CA3M', 'CA3 mensuelle'), ('CA3T', 'CA3 trimestrielle'), ('CA12', 'CA12'), ('FRANCHISE', 'Franchise'), ('EXO', 'Exonéré')], max_length=20),
        ),
    ]
