# Generated by Django 6.0.1 on 2026-01-29 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0003_remove_client_cfe_applicable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_maj_compta', models.DateField(blank=True, null=True)),
                ('dernier_mois_traite', models.CharField(blank=True, max_length=20, null=True)),
                ('periode_traitement', models.CharField(blank=True, max_length=50, null=True)),
                ('verifie', models.BooleanField(default=False)),
                ('commentaires', models.TextField(blank=True)),
                ('ca_franchise_tva', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('client_ue', models.BooleanField(default=False)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_comptable', to='dossiers.client')),
            ],
        ),
    ]
