# Generated by Django 6.0.2 on 2026-03-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_alter_client_regime_imposition'),
        ('dossiers', '0003_notificationpaie'),
    ]

    operations = [
    ]
