# Generated by Django 6.0.1 on 2026-01-29 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_suivicomptable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_tva', models.CharField(blank=True, max_length=20, null=True)),
                ('periodicite', models.CharField(blank=True, max_length=20, null=True)),
                ('derniere_declaration', models.DateField(blank=True, null=True)),
                ('prochaine_echeance', models.DateField(blank=True, null=True)),
                ('tva_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tva_collectee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tva_deductible', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commentaires', models.TextField(blank=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tva', to='dossiers.client')),
            ],
        ),
    ]
