# Generated by Django 6.0.2 on 2026-03-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_merge_20260310_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpaie',
            name='lu',
        ),
        migrations.AddField(
            model_name='notificationpaie',
            name='lu_cabinet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpaie',
            name='lu_partenaire',
            field=models.BooleanField(default=False),
        ),
    ]
