# Generated by Django 6.0.2 on 2026-04-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0005_remove_notificationpaie_lu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('PAIE_VALIDEE', 'Validation du mois de paie'), ('BS_DSN_VALIDES', 'Validation BS + DSN')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
