# Generated by Django 6.0.1 on 2026-01-29 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0005_tva'),
    ]

    operations = [
        migrations.CreateModel(
            name='IS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_is', models.CharField(blank=True, max_length=50, null=True)),
                ('taux_is', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('derniere_declaration', models.DateField(blank=True, null=True)),
                ('prochaine_echeance', models.DateField(blank=True, null=True)),
                ('acompte_1', models.DateField(blank=True, null=True)),
                ('acompte_2', models.DateField(blank=True, null=True)),
                ('acompte_3', models.DateField(blank=True, null=True)),
                ('acompte_4', models.DateField(blank=True, null=True)),
                ('solde_is', models.DateField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='is_fiscal', to='dossiers.client')),
            ],
        ),
    ]
