# Generated by Django 6.0.2 on 2026-04-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0006_notificationemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationemail',
            name='event',
            field=models.CharField(choices=[('PAIE_VALIDEE', 'Validation du mois de paie'), ('BS_FAIT', 'Bulletins de salaire faits'), ('DSN_FAITE', 'DSN faite')], max_length=50),
        ),
    ]
