# Generated by Django 6.0.1 on 2026-01-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0006_is'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='is',
            name='regime_is',
        ),
        migrations.RemoveField(
            model_name='tva',
            name='periodicite',
        ),
        migrations.RemoveField(
            model_name='tva',
            name='regime_tva',
        ),
        migrations.RemoveField(
            model_name='tva',
            name='tva_collectee',
        ),
        migrations.RemoveField(
            model_name='tva',
            name='tva_deductible',
        ),
        migrations.RemoveField(
            model_name='tva',
            name='tva_due',
        ),
        migrations.AddField(
            model_name='tva',
            name='tva_aout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tva',
            name='tva_avril',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tva',
            name='tva_decembre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tva',
            name='tva_fevrier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tva',
            name='tva_janvier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tva',
            name='tva_juillet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tva',
            name='tva_juin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tva',
            name='tva_mai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tva',
            name='tva_mars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tva',
            name='tva_novembre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tva',
            name='tva_octobre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tva',
            name='tva_septembre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='periodicite',
            field=models.CharField(blank=True, choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel'), ('REGULIER', 'Régulier')], max_length=20, null=True, verbose_name='Périodicité de la saisie'),
        ),
        migrations.AlterField(
            model_name='is',
            name='acompte_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='is',
            name='acompte_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='is',
            name='acompte_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='is',
            name='acompte_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='is',
            name='derniere_declaration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant de la dernière déclaration'),
        ),
        migrations.AlterField(
            model_name='is',
            name='solde_is',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='suivicomptable',
            name='periode_traitement',
            field=models.CharField(blank=True, choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel'), ('REGULIER', 'Régulier')], max_length=20, null=True, verbose_name='Période de traitement'),
        ),
    ]
