# Generated by Django 6.0.1 on 2026-01-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0007_remove_is_regime_is_remove_tva_periodicite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tva',
            name='derniere_declaration',
        ),
        migrations.RemoveField(
            model_name='tva',
            name='prochaine_echeance',
        ),
    ]
