# Generated by Django 6.0.2 on 2026-04-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0007_alter_notificationemail_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('destinataire', models.EmailField(max_length=254)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='envoyé', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
