# Generated by Django 6.0.1 on 2026-01-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0008_remove_tva_derniere_declaration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tva',
            name='statut_aout',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
        migrations.AddField(
            model_name='tva',
            name='statut_avril',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
        migrations.AddField(
            model_name='tva',
            name='statut_decembre',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
        migrations.AddField(
            model_name='tva',
            name='statut_fevrier',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
        migrations.AddField(
            model_name='tva',
            name='statut_janvier',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
        migrations.AddField(
            model_name='tva',
            name='statut_juillet',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
        migrations.AddField(
            model_name='tva',
            name='statut_juin',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
        migrations.AddField(
            model_name='tva',
            name='statut_mai',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
        migrations.AddField(
            model_name='tva',
            name='statut_mars',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
        migrations.AddField(
            model_name='tva',
            name='statut_novembre',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
        migrations.AddField(
            model_name='tva',
            name='statut_octobre',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
        migrations.AddField(
            model_name='tva',
            name='statut_septembre',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
    ]
