# Generated by Django 6.0.2 on 2026-06-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0009_notificationpaielu'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpdeclaration',
            name='etat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dpdeclaration',
            name='status',
            field=models.CharField(blank=True, choices=[('blanc', 'Blanc'), ('orange', 'Orange'), ('vert', 'Vert')], default='blanc', max_length=20, null=True),
        ),
    ]
