# Generated by Django 6.0.1 on 2026-01-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0009_tva_statut_aout_tva_statut_avril_tva_statut_decembre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivicomptable',
            name='saisi_par',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
