# Generated by Django 6.0.2 on 2026-06-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0010_dpdeclaration_etat_dpdeclaration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isdeclaration',
            name='acompte_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='isdeclaration',
            name='acompte_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='isdeclaration',
            name='acompte_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='isdeclaration',
            name='acompte_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='isdeclaration',
            name='is_n_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='isdeclaration',
            name='is_n_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='isdeclaration',
            name='solde',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_acompte_1',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_acompte_2',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_aout',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_avril',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_decembre',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_fevrier',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_janvier',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_juillet',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_juin',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_mai',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_mars',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_novembre',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_octobre',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_septembre',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_solde',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_t1',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_t2',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_t3',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_t4',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('BLANC', 'Rejeté')], default='NONE', max_length=20),
        ),
    ]
