# Generated by Django 6.0.1 on 2026-01-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0010_suivicomptable_saisi_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='jour_echeance_tva',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Jour du mois pour l'échéance TVA (1 à 31)", null=True),
        ),
    ]
