# Generated by Django 6.0.2 on 2026-06-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0011_alter_isdeclaration_acompte_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='isdeclaration',
            name='total_is',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
