# Generated by Django 6.0.1 on 2026-01-30 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0011_client_jour_echeance_tva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suivicomptable',
            name='ca_franchise_tva',
        ),
        migrations.RemoveField(
            model_name='suivicomptable',
            name='client_ue',
        ),
        migrations.RemoveField(
            model_name='suivicomptable',
            name='commentaires',
        ),
        migrations.AddField(
            model_name='is',
            name='annee',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='suivicomptable',
            name='annee',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='tva',
            name='annee',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='is',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_fiscaux', to='dossiers.client'),
        ),
        migrations.AlterField(
            model_name='suivicomptable',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dossiers.client'),
        ),
        migrations.AlterField(
            model_name='suivicomptable',
            name='periode_traitement',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tva',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvas', to='dossiers.client'),
        ),
    ]
