# Generated by Django 6.0.1 on 2026-01-30 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0012_remove_suivicomptable_ca_franchise_tva_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suivicomptable',
            options={'verbose_name': 'Suivi comptable', 'verbose_name_plural': 'Suivis comptables'},
        ),
        migrations.AlterField(
            model_name='suivicomptable',
            name='annee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suivicomptable',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.client'),
        ),
        migrations.AlterField(
            model_name='suivicomptable',
            name='periode_traitement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='suivicomptable',
            unique_together={('client', 'annee')},
        ),
    ]
