# Generated by Django 6.0.2 on 2026-06-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0012_isdeclaration_total_is'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfedeclaration',
            name='total_cfe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cfedeclaration',
            name='acompte_cfe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cfedeclaration',
            name='cfe_n_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cfedeclaration',
            name='solde_cfe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cfedeclaration',
            name='statut_1447c',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cfedeclaration',
            name='statut_acompte',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cfedeclaration',
            name='statut_solde',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
