# Generated by Django 6.0.2 on 2026-06-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0013_cfedeclaration_total_cfe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvaedeclaration',
            name='total_cvae',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cvaedeclaration',
            name='acompte_cvae',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cvaedeclaration',
            name='cvae_n_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cvaedeclaration',
            name='solde_cvae',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
