# Generated by Django 6.0.1 on 2026-01-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0013_alter_suivicomptable_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='is',
            options={'verbose_name': 'IS', 'verbose_name_plural': 'IS fiscaux'},
        ),
        migrations.AddField(
            model_name='is',
            name='statut_acompte_1',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
        migrations.AddField(
            model_name='is',
            name='statut_acompte_2',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
        migrations.AddField(
            model_name='is',
            name='statut_acompte_3',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
        migrations.AddField(
            model_name='is',
            name='statut_acompte_4',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
        migrations.AlterField(
            model_name='is',
            name='annee',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='is',
            unique_together={('client', 'annee')},
        ),
    ]
