# Generated by Django 6.0.1 on 2026-02-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0014_alter_is_options_is_statut_acompte_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_cloture',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='regime_imposition',
            field=models.CharField(blank=True, choices=[('IS', 'IS'), ('IR', 'IR'), ('RS', 'Réel simplifié'), ('RN', 'Réel normal'), ('MICRO', 'Micro'), ('IR_CRL', 'IR (CRL)')], max_length=20, null=True),
        ),
    ]
