# Generated by Django 6.0.2 on 2026-06-03 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0014_cvaedeclaration_total_cvae_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvsdeclaration',
            name='date_achat',
        ),
        migrations.RemoveField(
            model_name='tvsdeclaration',
            name='date_cession',
        ),
        migrations.RemoveField(
            model_name='tvsdeclaration',
            name='info_vehicule',
        ),
        migrations.RemoveField(
            model_name='tvsdeclaration',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='tvsdeclaration',
            name='vehicule',
        ),
        migrations.AddField(
            model_name='tvsdeclaration',
            name='commentaire_global',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tvsdeclaration',
            name='total_tvs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tvsdeclaration',
            name='tvs_n_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='TVSVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(blank=True, max_length=255)),
                ('modele', models.CharField(blank=True, max_length=255)),
                ('immatriculation', models.CharField(blank=True, max_length=50)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('date_cession', models.DateField(blank=True, null=True)),
                ('puissance_fiscale', models.CharField(blank=True, max_length=50)),
                ('montant_tvs', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_tvs', models.CharField(blank=True, max_length=20, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='dossiers.tvsdeclaration')),
            ],
        ),
    ]
