# Generated by Django 6.0.1 on 2026-02-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0015_alter_client_date_cloture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='module_cfe',
            field=models.BooleanField(default=False, verbose_name='CFE'),
        ),
        migrations.AddField(
            model_name='client',
            name='module_cloture',
            field=models.BooleanField(default=False, verbose_name='Clôture'),
        ),
        migrations.AddField(
            model_name='client',
            name='module_cvae',
            field=models.BooleanField(default=False, verbose_name='CVAE'),
        ),
        migrations.AddField(
            model_name='client',
            name='module_dividendes',
            field=models.BooleanField(default=False, verbose_name='Dividendes'),
        ),
        migrations.AddField(
            model_name='client',
            name='module_ir',
            field=models.BooleanField(default=False, verbose_name='IR personnel'),
        ),
        migrations.AddField(
            model_name='client',
            name='module_saisie',
            field=models.BooleanField(default=False, verbose_name='Saisie comptable'),
        ),
        migrations.AddField(
            model_name='client',
            name='module_social',
            field=models.BooleanField(default=False, verbose_name='Social'),
        ),
        migrations.AddField(
            model_name='client',
            name='module_suivi_mission',
            field=models.BooleanField(default=False, verbose_name='Suivi mission et LAB'),
        ),
        migrations.AddField(
            model_name='client',
            name='module_tvs',
            field=models.BooleanField(default=False, verbose_name='TVS'),
        ),
    ]
