# Generated by Django 6.0.2 on 2026-06-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0015_remove_tvsdeclaration_date_achat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='regime_tva',
            field=models.CharField(blank=True, choices=[('CA3M', 'CA3 mensuelle'), ('CA3T', 'CA3 trimestrielle'), ('CA12', 'CA12'), ('FRANCHISE', 'Franchise'), ('EXO', 'Exonéré')], max_length=20, null=True),
        ),
    ]
