# Generated by Django 6.0.2 on 2026-06-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0016_alter_client_regime_tva'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeuilFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Seuil fiscal',
                'verbose_name_plural': 'Seuils fiscaux',
                'unique_together': {('module', 'code')},
            },
        ),
    ]
