# Generated by Django 6.0.2 on 2026-06-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0017_seuilfiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvaedeclaration',
            name='acompte2_cvae',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cvaedeclaration',
            name='statut_acompte2_cvae',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
