# Generated by Django 6.0.1 on 2026-02-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0017_client_module_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivicomptable',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
