# Generated by Django 6.0.2 on 2026-06-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0018_cvaedeclaration_acompte2_cvae_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_acompte_1',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_acompte_2',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_aout',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_avril',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_decembre',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_fevrier',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_janvier',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_juillet',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_juin',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_mai',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_mars',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_novembre',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_octobre',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_septembre',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_solde',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_t1',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_t2',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_t3',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_t4',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], default='NONE', max_length=20),
        ),
    ]
