# Generated by Django 6.0.1 on 2026-02-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0018_suivicomptable_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tva',
            name='statut_aout',
            field=models.CharField(blank=True, choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tva',
            name='statut_avril',
            field=models.CharField(blank=True, choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tva',
            name='statut_decembre',
            field=models.CharField(blank=True, choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tva',
            name='statut_fevrier',
            field=models.CharField(blank=True, choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tva',
            name='statut_janvier',
            field=models.CharField(blank=True, choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tva',
            name='statut_juillet',
            field=models.CharField(blank=True, choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tva',
            name='statut_juin',
            field=models.CharField(blank=True, choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tva',
            name='statut_mai',
            field=models.CharField(blank=True, choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tva',
            name='statut_mars',
            field=models.CharField(blank=True, choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tva',
            name='statut_novembre',
            field=models.CharField(blank=True, choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tva',
            name='statut_octobre',
            field=models.CharField(blank=True, choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tva',
            name='statut_septembre',
            field=models.CharField(blank=True, choices=[('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], max_length=20, null=True),
        ),
    ]
