# Generated by Django 6.0.2 on 2026-07-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0019_alter_tvadeclaration_statut_acompte_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvadeclaration',
            name='user_aout',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='user_avril',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='user_decembre',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='user_fevrier',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='user_janvier',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='user_juillet',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='user_juin',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='user_mai',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='user_mars',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='user_novembre',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='user_octobre',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='user_septembre',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
