# Generated by Django 6.0.1 on 2026-02-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0019_alter_tva_statut_aout_alter_tva_statut_avril_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tva',
            name='statut_1t',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tva',
            name='statut_2t',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tva',
            name='statut_3t',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tva',
            name='statut_4t',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tva',
            name='tva_1t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tva',
            name='tva_2t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tva',
            name='tva_3t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tva',
            name='tva_4t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
