# Generated by Django 6.0.2 on 2026-07-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0020_tvadeclaration_user_aout_tvadeclaration_user_avril_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendesdeclaration',
            name='statut_2561',
            field=models.CharField(blank=True, choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dividendesdeclaration',
            name='statut_2777d',
            field=models.CharField(blank=True, choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dividendesdeclaration',
            name='statut_dividendes',
            field=models.CharField(blank=True, choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client (orange)'), ('JAUNE', 'Envoyé client (jaune)'), ('VERT_CLAIR', 'Télétransmis (vert clair)'), ('VERT_FONCE', 'Accepté (vert foncé)'), ('ROUGE', 'Rejeté (rouge)'), ('NA', 'N/A (gris)')], max_length=20, null=True),
        ),
    ]
