# Generated by Django 6.0.1 on 2026-02-09 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0020_tva_statut_1t_tva_statut_2t_tva_statut_3t_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVA_CA12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('montant_n_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('s1_07', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_s1_07', models.CharField(blank=True, max_length=20, null=True)),
                ('s2_12', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_s2_12', models.CharField(blank=True, max_length=20, null=True)),
                ('commentaire_tva_sup_1000', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.client')),
            ],
            options={
                'unique_together': {('client', 'annee')},
            },
        ),
    ]
