# Generated by Django 6.0.2 on 2026-07-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0021_dividendesdeclaration_statut_2561_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationemail',
            name='event',
            field=models.CharField(choices=[('PAIE_VALIDEE', 'Validation du mois de paie'), ('BS_A_VERIFIER', 'BS à vérifier par le cabinet'), ('BS_VERIFIE', 'BS vérifié par le cabinet'), ('BS_FAIT', 'Bulletins de salaire faits'), ('DSN_FAITE', 'DSN faite')], max_length=50),
        ),
    ]
