# Generated by Django 6.0.1 on 2026-02-10 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0021_tva_ca12'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueTVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('regime_tva', models.CharField(choices=[('CA3M', 'CA3 mensuelle'), ('CA3T', 'CA3 trimestrielle'), ('CA12', 'CA12'), ('FRANCHISE', 'Franchise'), ('EXO', 'Exonéré')], max_length=20)),
                ('montant_n_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('s1_07', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('s2_12', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_s1_07', models.CharField(blank=True, max_length=20, null=True)),
                ('statut_s2_12', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.client')),
            ],
            options={
                'ordering': ['-annee'],
                'unique_together': {('client', 'annee')},
            },
        ),
    ]
