# Generated by Django 6.0.1 on 2026-02-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0022_historiquetva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiquetva',
            old_name='montant_n_1',
            new_name='ca12_montant_n_1',
        ),
        migrations.RenameField(
            model_name='historiquetva',
            old_name='s1_07',
            new_name='ca12_s1_07',
        ),
        migrations.RenameField(
            model_name='historiquetva',
            old_name='s2_12',
            new_name='ca12_s2_12',
        ),
        migrations.RenameField(
            model_name='historiquetva',
            old_name='statut_s1_07',
            new_name='ca12_statut_s1_07',
        ),
        migrations.RenameField(
            model_name='historiquetva',
            old_name='statut_s2_12',
            new_name='ca12_statut_s2_12',
        ),
        migrations.AddField(
            model_name='historiquetva',
            name='ca3t_statut_t1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historiquetva',
            name='ca3t_statut_t2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historiquetva',
            name='ca3t_statut_t3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historiquetva',
            name='ca3t_statut_t4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historiquetva',
            name='ca3t_t1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historiquetva',
            name='ca3t_t2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historiquetva',
            name='ca3t_t3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historiquetva',
            name='ca3t_t4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
