# Generated by Django 6.0.2 on 2026-09-01 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0023_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='dossiers.client'),
        ),
    ]
