# Generated by Django 6.0.1 on 2026-02-10 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0024_historiquetva_ca3m_m1_historiquetva_ca3m_m10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVAAnnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVAClientAnnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.client')),
            ],
        ),
        migrations.CreateModel(
            name='TVADeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tva_janvier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_janvier', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('tva_fevrier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_fevrier', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('tva_mars', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_mars', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('tva_avril', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_avril', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('tva_mai', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_mai', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('tva_juin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_juin', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('tva_juillet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_juillet', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('tva_aout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_aout', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('tva_septembre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_septembre', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('tva_octobre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_octobre', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('tva_novembre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_novembre', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('tva_decembre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_decembre', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('ca3t_t1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_t1', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('ca3t_t2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_t2', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('ca3t_t3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_t3', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('ca3t_t4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_t4', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('ca12_montant_n_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_n_1', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('ca12_s1_07', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_s1_07', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('ca12_s2_12', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_s2_12', models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tva_client_annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='dossiers.tvaclientannee')),
            ],
        ),
        migrations.CreateModel(
            name='TVAModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CA3M', 'Mensuel'), ('CA3T', 'Trimestriel'), ('CA12', 'Annuel'), ('FR', 'Franchise'), ('EXO', 'Exonéré')], max_length=10)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='dossiers.tvaannee')),
            ],
        ),
        migrations.AddField(
            model_name='tvaclientannee',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='dossiers.tvamodule'),
        ),
        migrations.AlterUniqueTogether(
            name='tvaclientannee',
            unique_together={('module', 'client')},
        ),
    ]
