# Generated by Django 6.0.2 on 2026-09-01 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0024_alter_auditlog_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='URSSAFMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urssaf_janvier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_urssaf_janvier', models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client'), ('JAUNE', 'Envoyé client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('ROUGE', 'Rejeté'), ('NA', 'N/A')], default='BLANC', max_length=20)),
                ('urssaf_fevrier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_urssaf_fevrier', models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client'), ('JAUNE', 'Envoyé client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('ROUGE', 'Rejeté'), ('NA', 'N/A')], default='BLANC', max_length=20)),
                ('urssaf_mars', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_urssaf_mars', models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client'), ('JAUNE', 'Envoyé client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('ROUGE', 'Rejeté'), ('NA', 'N/A')], default='BLANC', max_length=20)),
                ('urssaf_avril', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_urssaf_avril', models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client'), ('JAUNE', 'Envoyé client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('ROUGE', 'Rejeté'), ('NA', 'N/A')], default='BLANC', max_length=20)),
                ('urssaf_mai', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_urssaf_mai', models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client'), ('JAUNE', 'Envoyé client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('ROUGE', 'Rejeté'), ('NA', 'N/A')], default='BLANC', max_length=20)),
                ('urssaf_juin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_urssaf_juin', models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client'), ('JAUNE', 'Envoyé client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('ROUGE', 'Rejeté'), ('NA', 'N/A')], default='BLANC', max_length=20)),
                ('urssaf_juillet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_urssaf_juillet', models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client'), ('JAUNE', 'Envoyé client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('ROUGE', 'Rejeté'), ('NA', 'N/A')], default='BLANC', max_length=20)),
                ('urssaf_aout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_urssaf_aout', models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client'), ('JAUNE', 'Envoyé client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('ROUGE', 'Rejeté'), ('NA', 'N/A')], default='BLANC', max_length=20)),
                ('urssaf_septembre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_urssaf_septembre', models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client'), ('JAUNE', 'Envoyé client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('ROUGE', 'Rejeté'), ('NA', 'N/A')], default='BLANC', max_length=20)),
                ('urssaf_octobre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_urssaf_octobre', models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client'), ('JAUNE', 'Envoyé client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('ROUGE', 'Rejeté'), ('NA', 'N/A')], default='BLANC', max_length=20)),
                ('urssaf_novembre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_urssaf_novembre', models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client'), ('JAUNE', 'Envoyé client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('ROUGE', 'Rejeté'), ('NA', 'N/A')], default='BLANC', max_length=20)),
                ('urssaf_decembre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_urssaf_decembre', models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client'), ('JAUNE', 'Envoyé client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('ROUGE', 'Rejeté'), ('NA', 'N/A')], default='BLANC', max_length=20)),
                ('client_module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='urssaf_mensuelle', to='dossiers.clientmodulefiscal')),
            ],
        ),
        migrations.CreateModel(
            name='URSSAFTrimestrielle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urssaf_1tri', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_urssaf_1tri', models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client'), ('JAUNE', 'Envoyé client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('ROUGE', 'Rejeté'), ('NA', 'N/A')], default='BLANC', max_length=20)),
                ('urssaf_2tri', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_urssaf_2tri', models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client'), ('JAUNE', 'Envoyé client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('ROUGE', 'Rejeté'), ('NA', 'N/A')], default='BLANC', max_length=20)),
                ('urssaf_3tri', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_urssaf_3tri', models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client'), ('JAUNE', 'Envoyé client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('ROUGE', 'Rejeté'), ('NA', 'N/A')], default='BLANC', max_length=20)),
                ('urssaf_4tri', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_urssaf_4tri', models.CharField(choices=[('BLANC', 'Blanc'), ('ORANGE', 'A envoyer client'), ('JAUNE', 'Envoyé client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté'), ('ROUGE', 'Rejeté'), ('NA', 'N/A')], default='BLANC', max_length=20)),
                ('client_module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='urssaf_trimestrielle', to='dossiers.clientmodulefiscal')),
            ],
        ),
    ]
