# Generated by Django 6.0.1 on 2026-02-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0025_tvaannee_tvaclientannee_tvadeclaration_tvamodule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvadeclaration',
            name='ca12_montant_n_1',
        ),
        migrations.RemoveField(
            model_name='tvadeclaration',
            name='ca12_s1_07',
        ),
        migrations.RemoveField(
            model_name='tvadeclaration',
            name='ca12_s2_12',
        ),
        migrations.RemoveField(
            model_name='tvadeclaration',
            name='statut_n_1',
        ),
        migrations.RemoveField(
            model_name='tvadeclaration',
            name='statut_s1_07',
        ),
        migrations.RemoveField(
            model_name='tvadeclaration',
            name='statut_s2_12',
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='commentaire_tva_plus_1000',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='statut_acompte_1',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='statut_acompte_2',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='statut_solde',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='tva_acompte_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='tva_acompte_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='tva_n_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tvadeclaration',
            name='tva_solde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
