# Generated by Django 6.0.1 on 2026-02-10 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0026_remove_tvadeclaration_ca12_montant_n_1_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tvaclientannee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tvaclientannee',
            name='annee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dossiers.tvaannee'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tvaclientannee',
            unique_together={('client', 'annee', 'module')},
        ),
    ]
