# Generated by Django 6.0.1 on 2026-02-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0027_alter_tvaclientannee_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivicomptable',
            name='ca_actuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='suivicomptable',
            name='saisie_en_cours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suivicomptable',
            name='saisie_terminee',
            field=models.BooleanField(default=False),
        ),
    ]
