# Generated by Django 6.0.1 on 2026-02-12 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0028_suivicomptable_ca_actuel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeFiscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientModuleFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.anneefiscale')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.client')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.modulefiscal')),
            ],
            options={
                'unique_together': {('client', 'module', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='ISDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_n_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_n_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acompte_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_acompte_1', models.CharField(blank=True, max_length=20, null=True)),
                ('acompte_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_acompte_2', models.CharField(blank=True, max_length=20, null=True)),
                ('acompte_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_acompte_3', models.CharField(blank=True, max_length=20, null=True)),
                ('acompte_4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_acompte_4', models.CharField(blank=True, max_length=20, null=True)),
                ('solde', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_solde', models.CharField(blank=True, max_length=20, null=True)),
                ('commentaire_plus_3000', models.TextField(blank=True, null=True)),
                ('client_module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='is_declaration', to='dossiers.clientmodulefiscal')),
            ],
        ),
    ]
