# Generated by Django 6.0.1 on 2026-02-13 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0029_anneefiscale_modulefiscal_clientmodulefiscal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFEDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfe_n_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('acompte_cfe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('solde_cfe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut_acompte', models.CharField(choices=[('payé', 'Payé'), ('en_attente', 'En attente'), ('non_concerne', 'Non concerné'), ('en_retard', 'En retard')], default='en_attente', max_length=20)),
                ('statut_solde', models.CharField(choices=[('payé', 'Payé'), ('en_attente', 'En attente'), ('non_concerne', 'Non concerné'), ('en_retard', 'En retard')], default='en_attente', max_length=20)),
                ('statut_1447c', models.CharField(choices=[('payé', 'Payé'), ('en_attente', 'En attente'), ('non_concerne', 'Non concerné'), ('en_retard', 'En retard')], default='non_concerne', max_length=20)),
                ('mode_paiement', models.CharField(blank=True, max_length=100)),
                ('degrevement', models.CharField(blank=True, max_length=255)),
                ('formulaire_1447c', models.CharField(blank=True, max_length=255)),
                ('commentaire_plus_3000', models.TextField(blank=True)),
                ('client_module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cfe_declaration', to='dossiers.clientmodulefiscal')),
            ],
        ),
    ]
