# Generated by Django 6.0.1 on 2026-02-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0031_alter_cfedeclaration_statut_1447c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_acompte_1',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_acompte_2',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_aout',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_avril',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_decembre',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_fevrier',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_janvier',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_juillet',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_juin',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_mai',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_mars',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_novembre',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_octobre',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_septembre',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_solde',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_t1',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_t2',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_t3',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvadeclaration',
            name='statut_t4',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'A envoyer au client'), ('VERT_CLAIR', 'Télétransmis'), ('VERT_FONCE', 'Accepté')], default='NONE', max_length=20),
        ),
    ]
