# Generated by Django 6.0.1 on 2026-02-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0035_alter_cfedeclaration_statut_1447c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfedeclaration',
            name='statut_1447c',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
        migrations.AlterField(
            model_name='cfedeclaration',
            name='statut_acompte',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
        migrations.AlterField(
            model_name='cfedeclaration',
            name='statut_solde',
            field=models.CharField(choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20),
        ),
    ]
