# Generated by Django 6.0.1 on 2026-02-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0036_alter_cfedeclaration_statut_1447c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isdeclaration',
            name='statut_acompte_1',
            field=models.CharField(blank=True, choices=[('NONE', 'Sans pastille'), ('BLANC', 'Blanc'), ('JAUNE', 'Jaune'), ('VERT_CLAIR', 'Vert clair'), ('VERT_FONCE', 'Vert foncé')], default='BLANC', max_length=20, null=True),
        ),
    ]
