# Generated by Django 6.0.1 on 2026-02-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0038_alter_isdeclaration_statut_acompte_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isdeclaration',
            name='statut_acompte_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='isdeclaration',
            name='statut_acompte_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='isdeclaration',
            name='statut_acompte_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='isdeclaration',
            name='statut_acompte_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='isdeclaration',
            name='statut_solde',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
