# Generated by Django 6.0.1 on 2026-02-13 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0039_alter_isdeclaration_statut_acompte_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVAEDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvae_n_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('acompte_cvae', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut_acompte_cvae', models.CharField(blank=True, max_length=20, null=True)),
                ('solde_cvae', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut_solde_cvae', models.CharField(blank=True, max_length=20, null=True)),
                ('commentaire_plus_1500', models.TextField(blank=True, null=True)),
                ('client_module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cvae_declaration', to='dossiers.clientmodulefiscal')),
            ],
        ),
    ]
