# Generated by Django 6.0.1 on 2026-02-13 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0040_cvaedeclaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVSDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvs_n_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vehicule', models.BooleanField(default=False)),
                ('soumis_tvs_n', models.BooleanField(default=False)),
                ('formulaire', models.CharField(blank=True, max_length=255, null=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut_tvs', models.CharField(blank=True, max_length=20, null=True)),
                ('info_vehicule', models.CharField(blank=True, max_length=255, null=True)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('date_cession', models.DateField(blank=True, null=True)),
                ('client_module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tvs_declaration', to='dossiers.clientmodulefiscal')),
            ],
        ),
    ]
