# Generated by Django 6.0.1 on 2026-02-13 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0041_tvsdeclaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DESDEBDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('retour_client', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_janvier', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_janvier', models.CharField(blank=True, max_length=20, null=True)),
                ('ref_fevrier', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_fevrier', models.CharField(blank=True, max_length=20, null=True)),
                ('ref_mars', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_mars', models.CharField(blank=True, max_length=20, null=True)),
                ('ref_avril', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_avril', models.CharField(blank=True, max_length=20, null=True)),
                ('ref_mai', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_mai', models.CharField(blank=True, max_length=20, null=True)),
                ('ref_juin', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_juin', models.CharField(blank=True, max_length=20, null=True)),
                ('ref_juillet', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_juillet', models.CharField(blank=True, max_length=20, null=True)),
                ('ref_aout', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_aout', models.CharField(blank=True, max_length=20, null=True)),
                ('ref_septembre', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_septembre', models.CharField(blank=True, max_length=20, null=True)),
                ('ref_octobre', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_octobre', models.CharField(blank=True, max_length=20, null=True)),
                ('ref_novembre', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_novembre', models.CharField(blank=True, max_length=20, null=True)),
                ('ref_decembre', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_decembre', models.CharField(blank=True, max_length=20, null=True)),
                ('client_module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desdeclaration', to='dossiers.clientmodulefiscal')),
            ],
        ),
    ]
