# Generated by Django 6.0.1 on 2026-02-13 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0042_desdebdeclaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendesDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('date_2777d', models.DateField(blank=True, null=True)),
                ('date_2561', models.DateField(blank=True, null=True)),
                ('annee_versement', models.CharField(blank=True, max_length=10, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('statut_dividendes', models.CharField(blank=True, max_length=20, null=True)),
                ('client_module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dividendes_declaration', to='dossiers.clientmodulefiscal')),
            ],
        ),
    ]
