# Generated by Django 6.0.1 on 2026-02-13 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0043_dividendesdeclaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier_deontologie', models.CharField(blank=True, max_length=255, null=True)),
                ('acceptation_lab', models.CharField(blank=True, max_length=255, null=True)),
                ('piece_identite', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(blank=True, max_length=255, null=True)),
                ('bail', models.CharField(blank=True, max_length=255, null=True)),
                ('lettre_mission', models.CharField(blank=True, max_length=255, null=True)),
                ('avenant', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dp', to='dossiers.client')),
            ],
        ),
    ]
