# Generated by Django 6.0.1 on 2026-02-15 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0045_clientnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientnote',
            options={},
        ),
        migrations.CreateModel(
            name='NoteCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.client')),
            ],
        ),
        migrations.AddField(
            model_name='clientnote',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dossiers.notecategorie'),
        ),
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.client')),
            ],
        ),
        migrations.AddField(
            model_name='clientnote',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dossiers.notetag'),
        ),
    ]
