# Generated by Django 6.0.1 on 2026-02-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0050_todo_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='recurrence_day',
            field=models.PositiveIntegerField(blank=True, help_text='Jour du mois pour la récurrence', null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'Aucune'), ('monthly_first', 'Tous les 1er du mois'), ('monthly_day', 'Tous les mois le jour choisi')], default='none', max_length=20),
        ),
    ]
