# Generated by Django 6.0.1 on 2026-02-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0052_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='module_paie',
            field=models.BooleanField(default=False, verbose_name='Module Paie'),
        ),
    ]
