# Generated by Django 6.0.1 on 2026-02-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0054_clotureannee_clotureclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clotureclient',
            name='ca12_envoi_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='ca12_faite_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='ca12_tva_aic_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='cvae_1130_envoi_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='cvae_1329def_fait_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='cvae_1329dev_envoi_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='cvae_1330_fait_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='das2_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='decloyer_envoi_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='decloyer_fait_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='dri_envoi_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='dri_fait_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='envoi_liasse_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='is_envoi_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='is_fait_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='juridique_envoi_client_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='juridique_envoi_greffe_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='juridique_fait_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='juridique_retour_client_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='juridique_validation_greffe_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='liasse_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='mission_attestation_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='mission_cr_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='mission_dossier_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='mission_lab_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='plaquettes_envoi_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='plaquettes_retour_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='pre_revision_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='relance_pieces_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='releve_decembre_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
        migrations.AlterField(
            model_name='clotureclient',
            name='revision_statut',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('jaune', 'Jaune'), ('vert_clair', 'Vert clair'), ('vert_fonce', 'Vert foncé')], default='transparent', max_length=20),
        ),
    ]
