# Generated by Django 6.0.1 on 2026-02-27 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaieMois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('client_valide', models.BooleanField(default=False)),
                ('partenaire_valide', models.BooleanField(default=False)),
                ('date_validation_client', models.DateTimeField(blank=True, null=True)),
                ('date_validation_partenaire', models.DateTimeField(blank=True, null=True)),
                ('bs_fait', models.BooleanField(default=False)),
                ('dsn_faite', models.BooleanField(default=False)),
                ('date_bs_fait', models.DateTimeField(blank=True, null=True)),
                ('date_dsn_faite', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.client')),
            ],
            options={
                'ordering': ['-annee', '-mois'],
                'unique_together': {('client', 'annee', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='Salarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('numero_securite_sociale', models.CharField(blank=True, max_length=15)),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('mutuelle', models.CharField(blank=True, max_length=200)),
                ('salaire_base', models.CharField(blank=True, max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='dossiers.client')),
            ],
        ),
        migrations.CreateModel(
            name='VariablePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_sup_25', models.TextField(blank=True)),
                ('heures_sup_50', models.TextField(blank=True)),
                ('primes', models.TextField(blank=True)),
                ('conges_debut', models.TextField(blank=True)),
                ('conges_fin', models.TextField(blank=True)),
                ('absences_maladie', models.TextField(blank=True)),
                ('absences_autres', models.TextField(blank=True)),
                ('acomptes', models.TextField(blank=True)),
                ('autres_infos', models.TextField(blank=True)),
                ('paie_mois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paie.paiemois')),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paie.salarie')),
            ],
            options={
                'unique_together': {('paie_mois', 'salarie')},
            },
        ),
    ]
