# Generated by Django 6.0.1 on 2026-02-21 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0051_todo_recurrence_day_todo_recurrence_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaieMois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('client_valide', models.BooleanField(default=False)),
                ('partenaire_valide', models.BooleanField(default=False)),
                ('date_validation_client', models.DateTimeField(blank=True, null=True)),
                ('date_validation_partenaire', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.client')),
            ],
            options={
                'ordering': ['-annee', '-mois'],
                'unique_together': {('client', 'annee', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='Salarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.client')),
            ],
        ),
        migrations.CreateModel(
            name='VariablePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('primes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('absences', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('paie_mois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paie.paiemois')),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paie.salarie')),
            ],
            options={
                'unique_together': {('paie_mois', 'salarie')},
            },
        ),
    ]
