# Generated by Django 6.0.2 on 2026-04-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiemois',
            options={'ordering': ['-annee', '-mois'], 'verbose_name': 'Paie mois', 'verbose_name_plural': 'Paie mois'},
        ),
    ]
