# Generated by Django 6.0.1 on 2026-02-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiemois',
            options={'ordering': ['-annee', '-mois'], 'verbose_name': 'Mois de paie', 'verbose_name_plural': 'Mois de paie'},
        ),
    ]
