# Generated by Django 6.0.1 on 2026-02-21 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0053_client_module_paie'),
        ('paie', '0002_alter_paiemois_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='numero_securite_sociale',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='dossiers.client'),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='date_entree',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
    ]
