# Generated by Django 6.0.2 on 2026-06-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0002_alter_paiemois_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='apprenti',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salarie',
            name='cdd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salarie',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='temps_partiel',
            field=models.BooleanField(default=False),
        ),
    ]
