# Generated by Django 6.0.1 on 2026-02-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0003_salarie_actif_salarie_date_naissance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variablepaie',
            name='absences',
        ),
        migrations.RemoveField(
            model_name='variablepaie',
            name='heures',
        ),
        migrations.AddField(
            model_name='variablepaie',
            name='absences_autres',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='variablepaie',
            name='absences_maladie',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='variablepaie',
            name='acomptes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='variablepaie',
            name='autres_infos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='variablepaie',
            name='conges_debut',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='variablepaie',
            name='conges_fin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='variablepaie',
            name='heures_sup_25',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='variablepaie',
            name='heures_sup_50',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='variablepaie',
            name='primes',
            field=models.TextField(blank=True),
        ),
    ]
