# Generated by Django 6.0.2 on 2026-06-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0003_salarie_apprenti_salarie_cdd_salarie_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiemois',
            name='validation_forcee',
            field=models.BooleanField(default=False),
        ),
    ]
