# Generated by Django 6.0.2 on 2026-06-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0004_paiemois_validation_forcee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiemois',
            name='validation_forcee',
        ),
        migrations.AddField(
            model_name='paiemois',
            name='bs_force',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paiemois',
            name='dsn_force',
            field=models.BooleanField(default=False),
        ),
    ]
