# Generated by Django 6.0.1 on 2026-02-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0004_remove_variablepaie_absences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='mutuelle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salarie',
            name='salaire_base',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
