# Generated by Django 6.0.2 on 2026-06-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0005_remove_paiemois_validation_forcee_paiemois_bs_force_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiemois',
            name='client_valide_par_cabinet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paiemois',
            name='date_validation_par_cabinet',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
