# Generated by Django 6.0.1 on 2026-02-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0005_salarie_mutuelle_salarie_salaire_base'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiemois',
            options={'ordering': ['-annee', '-mois']},
        ),
        migrations.AddField(
            model_name='paiemois',
            name='bs_fait',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paiemois',
            name='date_bs_fait',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiemois',
            name='date_dsn_faite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiemois',
            name='dsn_faite',
            field=models.BooleanField(default=False),
        ),
    ]
