# Generated by Django 6.0.2 on 2026-07-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0006_paiemois_client_valide_par_cabinet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiemois',
            name='bs_a_verifier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paiemois',
            name='bs_verifie_par_cabinet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paiemois',
            name='date_bs_a_verifier',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiemois',
            name='date_bs_verifie_par_cabinet',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
